### ISSUE TITLE
SQLMap API not starting

### ISSUE THREAD

**Issue by rencep** [codewatchorg/sqlipy#46]
Good day,

I'm trying to run SQLMap Api on my Burp but it doesn't start, 

Windows OS: Windows 11
Burp: 2024.9.5
Python 3.13.0
jython 2.7.0

![Screenshot 2024-11-12 191531](https://github.com/user-attachments/assets/ac3c55e3-d814-4984-8dc4-dcf1297e09cf)

```

PS C:\Users\> python C:\Users\AppData\Roaming\BurpSuite\bapps\f154175126a04bfe8edc6056f340f52e\sqlmap\sqlmapapi.py
Traceback (most recent call last):
  File "C:\Users\AppData\Roaming\BurpSuite\bapps\f154175126a04bfe8edc6056f340f52e\sqlmap\sqlmapapi.py", line 31, in <module>
    from lib.utils.api import client
  File "C:\Users\AppData\Roaming\BurpSuite\bapps\f154175126a04bfe8edc6056f340f52e\sqlmap\lib\utils\api.py", line 58, in <module>
    from thirdparty.bottle.bottle import error as return_error
  File "C:\Users\AppData\Roaming\BurpSuite\bapps\f154175126a04bfe8edc6056f340f52e\sqlmap\thirdparty\bottle\bottle.py", line 72, in <module>
    import base64, calendar, cgi, email.utils, functools, hmac, imp, itertools,\
           mimetypes, os, re, tempfile, threading, time, warnings, weakref, hashlib
ModuleNotFoundError: No module named 'cgi'

```

**Comment by codewatchorg** [comment]
Looks like that is a combination of the version of Python you are using with the version of sqlmap that is part of the extension: https://github.com/sqlmapproject/sqlmap/issues/5732.

I have some updates to make and will work to incorporate the latest version of sqlmap with those updates.

**Comment by codewatchorg** [comment]
It took me forever, but I have updated the version of sqlmap to the latest and greatest. Will work on a pull request for the Burp Bapp store.
